apiVersion: v1
kind: Service
metadata:
  name: spring-starbucks-cashier-service 
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080 
  selector:
    name: spring-starbucks-cashier