
version: "3"

services:
  mysql:
    image: mysql:8.0
    volumes:
      - /tmp:/tmp
    ports:
      - 3306  
    networks:
      - network   
    environment:
      MYSQL_ROOT_PASSWORD: "cmpe172"
    restart: always     
  starbucks:
    image: spring-starbucks-api
    depends_on:
      - mysql    
    volumes:
      - /tmp:/tmp  
    ports:
      - 8080:8080
    networks:
      - network  
    environment:
      MYSQL_HOST: "mysql"
    restart: always     
  lb:
    image: eeacms/haproxy
    depends_on:
      - starbucks
    ports:
      - "80:5000"
      - "1936:1936"
    environment:
      BACKENDS: "starbucks"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "true"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge

